### ISSUE TITLE
when I run the main.py, error occurred

### ISSUE THREAD

**Issue by stq054188** [adnaniazi/real-time-digit-classifier#1]
my environment: windows 10 , python3.5.1, tensorflow 1.10.0，scikit-image 0.15.0
Could you give me some advice? thank you very much! @adnaniazi
error message:
Traceback (most recent call last):
  File "C:\Users\A4080599\Desktop\real-time-digit-classifier-master\main.py", line 21, in <module>
    from skimage import util
  File "C:\Python35\lib\site-packages\skimage\__init__.py", line 127, in <module>
    from .util.dtype import (img_as_float32,
  File "C:\Python35\lib\site-packages\skimage\util\__init__.py", line 12, in <module>
    from ._montage import montage
  File "C:\Python35\lib\site-packages\skimage\util\_montage.py", line 2, in <module>
    from .. import exposure
  File "C:\Python35\lib\site-packages\skimage\exposure\__init__.py", line 1, in <module>
    from .exposure import histogram, equalize_hist, \
  File "C:\Python35\lib\site-packages\skimage\exposure\exposure.py", line 3, in <module>
    from ..color import rgb2gray
  File "C:\Python35\lib\site-packages\skimage\color\__init__.py", line 1, in <module>
    from .colorconv import (convert_colorspace,
  File "C:\Python35\lib\site-packages\skimage\color\colorconv.py", line 55, in <module>
    from scipy import linalg
  File "C:\Python35\lib\site-packages\scipy\__init__.py", line 156, in <module>
    from . import fft
  File "C:\Python35\lib\site-packages\scipy\fft\__init__.py", line 76, in <module>
    from ._basic import (
  File "C:\Python35\lib\site-packages\scipy\fft\_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "C:\Python35\lib\site-packages\scipy\_lib\uarray.py", line 27, in <module>
    from ._uarray import *
  File "C:\Python35\lib\site-packages\scipy\_lib\_uarray\__init__.py", line 114, in <module>
    from ._backend import *
  File "C:\Python35\lib\site-packages\scipy\_lib\_uarray\_backend.py", line 1, in <module>
    from typing import (
ImportError: cannot import name 'Type'

**Comment by stq054188** [comment]
I have sovled the problem by decreasing the version scipy to 1.2.1.
